name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building the project..."

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install pytest  # Install pytest
          # Install other dependencies if needed

      - name: Run tests
        run: |
          pytest  # Run pytest tests

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        env:
          OPENAI_SECRET_KEY: ${{ secrets.OPENAI_SECRET_KEY }}
        run: |
          echo "Deploying to production..."
          # Call your deployment script and pass the secret key as an environment variable
          ./deploy_script.sh $OPENAI_SECRET_KEY
